name: BLOG.DAICH.ORG
description: Everything is code.
meta_description: Everything is code.

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: http://blog.daich.org
google_analytics: UA-30550631-1
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url: http://blog.daich.org
author: Daichi HIRATA
authorTwitter: Daic_h

permalink: /:year/:month/:day/:title

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - .gitignore

defaults:
  - scope:
      path: "" # empty string for all files
      type: pages
    values:
      layout: default
  - scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: post
