domain_name: http://blog.daich.org
url: http://blog.daich.org
baseurl: /
permalink: /:year/:month/:day/:title/

name: blog.daich.org
description: Everything is code.
author: Daichi HIRATA
google_analytics: UA-30550631-1

timezone: Asia/Tokyo

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
- jemoji
- jekyll-coffeescript
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Rakefile
- .gitignore

defaults:
- scope:
    type: pages
  values:
    layout: default
- scope:
    type: posts
  values:
    layout: post
- scope:
    type: drafts
  values:
    layout: post
